//
//  Characters.swift
//  Betrayal at House on the Hill
//
//  Created by Sean Tesch on 10/25/21.
//

import Foundation
import UIKit

struct Characters {
    var characters = [
        Character(n: "Missy Dubourde",
                  c: UIColor.yellow,
                  a: 9,
                  b: DateComponents(year: 2012, month: 2, day: 14),
                  he: 50,
                  we: 82,
                  h: ["Swimming","Medicine"],
                  d: "A creepy little girl, who wants to be a doctor. She cuts up dead things, for fun. Missy then has nightmares about them.",
                  f: "Dead things coming back to life to haunt her.",
                  sp: [0,3,4,5,6,6,6,7,7],
                  mi: [0,2,3,3,3,4,5,6,7],
                  sa: [0,1,2,3,4,5,5,6,7],
                  kn: [0,2,3,4,4,5,6,6,6],
                  spI: 3,
                  miI: 4,
                  saI: 3,
                  knI: 4),
        
        Character(n: "Zoe Ingstrom",
                  c: UIColor.yellow,
                  a: 8,
                  b: DateComponents(year: 2013, month: 11, day: 5),
                  he: 45,
                  we: 49,
                  h: ["Dolls","Music"],
                  d: "Zoe has an implied tragic story. Raised in an unhappy home, she uses dolls to express her emotions.",
                  f: "The Boogeyman.",
                  sp: [0,4,4,4,4,5,6,8,8],
                  mi: [0,2,2,3,3,4,4,6,7],
                  sa: [0,3,4,5,5,6,6,7,8],
                  kn: [0,1,2,3,4,4,5,5,5],
                  spI: 4,
                  miI: 4,
                  saI: 3,
                  knI: 3),
        
        Character(n: "Jenny LeClerc",
                  c: UIColor.purple,
                  a: 21,
                  b: DateComponents(year: 2000, month: 3, day: 4),
                  he: 67,
                  we: 142,
                  h: ["Reading","Soccer (or Football for us Brits)"],
                  d: "A quiet bookworm whose mother disappeared when she was younger. Jenny feels always alone.",
                  f: "Being trapped in a crowd or lost in the open air.",
                  sp: [0,2,3,4,4,4,5,6,8],
                  mi: [0,3,4,4,4,4,5,6,8],
                  sa: [0,1,1,2,4,4,4,5,6],
                  kn: [0,2,3,3,4,4,5,6,8],
                  spI: 4,
                  miI: 3,
                  saI: 5,
                  knI: 3),
        
        Character(n: "Heather Granville",
                  c: UIColor.purple,
                  a: 18,
                  b: DateComponents(year: 2003, month: 8, day: 2),
                  he: 62,
                  we: 120,
                  h: ["Television","Shopping"],
                  d: "Seen as perfect in both her eyes and the eyes of others, when things aren’t perfect she suffers from headaches. She keeps smiling anyway.",
                  f: "Not being perfect.",
                  sp: [0,3,3,4,5,6,6,7,8],
                  mi: [0,3,3,3,4,5,6,7,8],
                  sa: [0,3,3,3,4,5,6,6,6],
                  kn: [0,2,3,3,4,5,6,7,8],
                  spI: 3,
                  miI: 3,
                  saI: 3,
                  knI: 5),
        
        Character(n: "Madame Zostra",
                  c: UIColor.blue,
                  a: 37,
                  b: DateComponents(year: 1984, month: 12, day: 10),
                  he: 60,
                  we: 150,
                  h: ["Astrology","Cooking","Baseball"],
                  d: "Also known as Belladina, Madame Zostra is a tarot card reader and tea-leaf reader with her own stay-at-home astrology business.",
                  f: "Death, especially that of her self.",
                  sp: [0,2,3,3,5,5,6,6,7],
                  mi: [0,2,3,3,4,5,5,5,6],
                  sa: [0,4,4,4,5,6,7,8,8],
                  kn: [0,1,3,4,4,4,5,6,6],
                  spI: 3,
                  miI: 4,
                  saI: 3,
                  knI: 4),
        
        Character(n: "Vivian Lopez",
                  c: UIColor.blue,
                  a: 42,
                  b: DateComponents(year: 1979, month: 1, day: 11),
                  he: 65,
                  we: 142,
                  h: ["Old Movies","Horses"],
                  d: "A small bookshop owner who, when finances become difficult, has thoughts of arson.",
                  f: "The same as one of her greatest loves – fire.",
                  sp: [0,3,4,4,4,4,6,7,8],
                  mi: [0,2,2,2,4,4,5,6,6],
                  sa: [0,4,4,4,5,6,7,8,8],
                  kn: [0,4,5,5,5,5,6,6,7],
                  spI: 4,
                  miI: 3,
                  saI: 3,
                  knI: 4),
        
        Character(n: "Darrin “Flash” Williams",
                  c: UIColor.red,
                  a: 20,
                  b: DateComponents(year: 2001, month: 6, day: 6),
                  he: 71,
                  we: 188,
                  h: ["Track","Music","Shakespearean Literature"],
                  d: "Flash is a paranoid runner, who can’t help but shake the feeling that something is chasing him.",
                  f: "Getting caught by that which is chasing him.",
                  sp: [0,4,4,4,5,6,7,7,8],
                  mi: [0,2,3,3,4,5,6,6,7],
                  sa: [0,1,2,3,4,5,5,5,7],
                  kn: [0,2,3,3,4,5,5,5,7],
                  spI: 5,
                  miI: 3,
                  saI: 3,
                  knI: 3),
        
        Character(n: "Ox Bellows",
                  c: UIColor.red,
                  a: 23,
                  b: DateComponents(year: 1998, month: 10, day: 18),
                  he: 76,
                  we: 288,
                  h: ["Football","Shiny Objects"],
                  d: "A big kid who once had to lash out. Ox is now haunted by his past and what he did that one time.",
                  f: "The dark.",
                  sp: [0,2,2,2,3,4,5,5,6],
                  mi: [0,4,5,5,6,6,7,8,8],
                  sa: [0,2,2,3,4,5,5,6,7],
                  kn: [0,2,2,3,3,5,5,6,6],
                  spI: 5,
                  miI: 3,
                  saI: 3,
                  knI: 3),
        
        Character(n: "Brandon Jaspers",
                  c: UIColor.green,
                  a: 12,
                  b: DateComponents(year: 2009, month: 5, day: 12),
                  he: 61,
                  we: 109,
                  h: ["Computers","Camping","Hockey"],
                  d: "A kid who never liked playing with traditional toys, Brandon could swear his old puppet was moving closer to him when he slept.",
                  f: "Puppets, especially those of the clown variety.",
                  sp: [0,3,4,4,4,5,6,7,8],
                  mi: [0,2,3,3,4,5,6,6,7],
                  sa: [0,3,3,3,4,5,6,7,8],
                  kn: [0,1,3,3,5,5,6,6,7],
                  spI: 3,
                  miI: 4,
                  saI: 4,
                  knI: 3),
        
        Character(n: "Peter Akimoto",
                  c: UIColor.green,
                  a: 13,
                  b: DateComponents(year: 2008, month: 9, day: 3),
                  he: 59,
                  we: 98,
                  h: ["Bugs","Basketball"],
                  d: "Seriously bullied by his family, Peter liked to hide under his house and look at bugs. He wants to be an entomologist.",
                  f: "Getting caught somewhere he can’t get out.",
                  sp: [0,3,3,3,4,6,6,7,7],
                  mi: [0,2,3,3,4,5,5,6,8],
                  sa: [0,3,4,4,4,5,6,6,7],
                  kn: [0,3,4,4,5,6,7,7,8],
                  spI: 4,
                  miI: 3,
                  saI: 4,
                  knI: 3),
        
        Character(n: "Father Rhinehardt",
                  c: UIColor.white,
                  a: 62,
                  b: DateComponents(year: 1959, month: 4, day: 29),
                  he: 69,
                  we: 185,
                  h: ["Fencing","Gardening"],
                  d: "A man who turned to religion to escape persecution, Father Rhinehardt is haunted by the mad whispers of the confessional booth.",
                  f: "Going mad.",
                  sp: [0,2,3,3,4,5,6,7,7],
                  mi: [0,1,2,2,4,4,5,5,7],
                  sa: [0,3,4,5,5,6,7,7,8],
                  kn: [0,1,3,3,4,5,6,6,8],
                  spI: 3,
                  miI: 3,
                  saI: 5,
                  knI: 4),
        
        Character(n: "Professor Longfellow",
                  c: UIColor.white,
                  a: 57,
                  b: DateComponents(year: 1964, month: 7, day: 27),
                  he: 71,
                  we: 153,
                  h: ["Gaelic Music","Drama","Fine Wines"],
                  d: "An aristocrat by birth, Professor Longfellow now lives with his mother, broke and wondering about her life insurance policy.",
                  f: "Losing everything he has.",
                  sp: [0,2,2,4,4,5,5,6,6],
                  mi: [0,1,2,3,4,5,5,6,6],
                  sa: [0,1,3,3,4,5,5,6,7],
                  kn: [0,4,5,5,5,5,6,7,8],
                  spI: 4,
                  miI: 3,
                  saI: 3,
                  knI: 5)
    ]
}
